# /etc/zsh/zprofile: system-wide .zprofile file for zsh(1).
#
# This file is sourced only for login shells (i.e. shells
# invoked with "-" as the first character of argv[0], and
# shells invoked with the -l flag.)
#
# Global Order: zshenv, zprofile, zshrc, zlogin

alias s='sudo su - root -s /usr/bin/zsh'

function hhtop {
    mkdir -p ~/.config/htop
    cp /etc/htoprc.global ~/.config/htop/htoprc
    htop
}

ZSH_THEME=bw
DISABLE_AUTO_UPDATE=true
plugins=(
  zsh-autosuggestions
)
source /etc/zsh/oh-my-zsh/oh-my-zsh.sh
