#!/bin/bash -l

sudo tee /etc/pam.d/sudo << EOT
# sudo: auth account password session
auth       sufficient     pam_tid.so
auth       sufficient     pam_smartcard.so
auth       required       pam_opendirectory.so
account    required       pam_permit.so
password   required       pam_deny.so
session    required       pam_permit.so
EOT

xcode-select --install

git -C ~/.zsh/oh-my-zsh pull

brew upgrade
brew upgrade --cask --greedy

pyenv install --keep-existing

sudo softwareupdate -ia --verbose

if test "$(defaults read com.apple.dock autohide-time-modifier)" == 0.16
then
    defaults write com.apple.dock autohide-time-modifier -float 0.16
    RESTART_DOCK=TRUE
fi

if test "$(defaults read com.apple.dock autohide-delay)" -ne 0
then
    defaults write com.apple.dock autohide-delay -float 0
    RESTART_DOCK=TRUE
fi

if test "$RESTART_DOCK" = TRUE
then
    killall Dock
fi

sudo systemsetup -setremotelogin on # enable ssh

pip install --upgrade pip
