#!/usr/bin/env bash

cd "$OLDPWD"

pyenv install --skip-existing

if test -f .venv/bin/python && test "$(realpath .venv/bin/python)" != "$(realpath "$(pyenv which python)")"
then
  echo "rebuilding venv für new python version"
  rm -rf .venv .pip_upgrade_timestamp
fi
