#!/bin/bash

UPTIME=$(cat /proc/uptime | cut -d. -f1)
MIN_UPTIME=$(expr 60 \* 20)
if [[ "$UPTIME" -lt "$MIN_UPTIME" ]]
then
  echo "ABORT: uptime ($UPTIME) lower than min ($MIN_UPTIME)"
  exit 0
fi

MY_SERVICE="$2"
for SERVICE in $(systemctl list-timers --no-pager --no-legend --state active -o json | jq -r '.[] | .activates')
do
  if [[ "$SERVICE" = "$MY_SERVICE" ]]
  then
    continue
  elif systemctl is-active "$SERVICE" --quiet
  then
    echo "ABORT: service $SERVICE is running by timer"
    exit 0
  fi
done

LOGINS=$(netstat -tnpa | grep 'ESTABLISHED.*sshd' | wc -l)
if [[ "$LOGINS" -gt 0 ]]
then
  echo "ABORT: $LOGINS user logins"
  exit 0
fi

if [[ "$1" = now ]]
then
  echo "SESPENDING"
  systemctl suspend
else
  echo "WOULD SESPEND"
fi
