#!/bin/bash
set -xeuo pipefail

function steam() {
    # for systemd, so it can terminate the process (for other things sudo would have been enough)
    setpriv --reuid=steam --regid=steam --init-groups "$@" <&0
    export HOME=/opt/l4d2/steam
}

function workshop() {
    steam mkdir -p "/opt/l4d2/overlays/${overlay}/left4dead2/addons"
    steam /opt/l4d2/scripts/steam-workshop-download --out "/opt/l4d2/overlays/${overlay}/left4dead2/addons" "$@"
}
