#!/bin/bash

if [[ '$1' == 'perform' ]]
then
  echo 'NON-DRY RUN'
  DRY=''
else
  echo 'DRY RUN'
  DRY='-n'
fi

% for dir, conf in dirs.items():
# ${dir}
gsutil ${'\\'}
  -m ${'\\'}
  -o 'GSUtil:parallel_process_count=${processes}' ${'\\'}
  -o 'GSUtil:parallel_thread_count=${threads}' ${'\\'}
  rsync ${'\\'}
    $DRY ${'\\'}
    -r ${'\\'}
    -d ${'\\'}
    -e ${'\\'}
    -x '${'|'.join(conf['exclude'])}' ${'\\'}
    '${dir}' ${'\\'}
    'gs://${bucket}/${node.name}${dir}'

% endfor
