#!/bin/bash

#set -x

gpio=$(expr 458 + 3)

# prepare
if ! [[ -e "/sys/class/gpio/gpio$gpio" ]]; then
  echo $gpio > "/sys/class/gpio/export"
fi

echo in > "/sys/class/gpio/gpio$gpio/direction"

# loop
previous_state=false
while sleep 0.001; do
  state=$(cat "/sys/class/gpio/gpio$gpio/value")
  if ! [[ "$state" = "$previous_state" ]] && [[ "$state" = 0 ]]
  then
    if ! [ -z $previous_impulse ] # skip first iteration
    then
      delay=$(expr $(date --utc +%s%N) - $previous_impulse)
      impulse_per_hour=$(expr 3600000000000 / $delay)
      watt=$(expr $impulse_per_hour / $(expr 2000 / 1000))
      echo $watt > /tmp/watt
      echo $delay $impulse_per_hour $watt
      # curl "https://${influxdb_domain}/ping" ${'\\'}
      #   -X POST ${'\\'}
      #   -H "Authentication: Token ${influxdb_token}" ${'\\'}
      #   -d "bucket=${influxdb_bucket}" ${'\\'}
      #   -d "ord=${influxdb_org}" ${'\\'}
      #   -d "data=powermeter,host=${node_name} watts=$watt"
    fi
    previous_impulse=$(date --utc +%s%N)
  fi
  previous_state=$state
done
